### ISSUE TITLE
[Feature Request] Add intent action to open specific module WebUI

### ISSUE THREAD

**Issue by Rem01Gaming** [5ec1cff/KsuWebUIStandalone#3]
Magisk 28.0 Introduced [Action button](https://github.com/topjohnwu/Magisk/releases/tag/v28.0) which essentially run action.sh script on the module root dir, by adding intent action to open WebUI essentially allow module developers open it's module WebUI on this app by a simple intent action command, turning action button to behave like "Open WebUI" button just like KernelSU and APatch.

This feature inspired by [Bellavita toast](https://xdaforums.com/t/req-very-small-app-to-display-toast-msg.773232/page-2) app that also uses same mechanism to display toast notification for modules, the command looks like this:
```shell
am start -a android.intent.action.MAIN -e toasttext "Testing toast notification" -n bellavita.toast/.MainActivity
```

**Comment by negroweed** [comment]
😨

**Comment by 5ec1cff** [comment]
```
am start -n io.github.a13e300.ksuwebui/.WebUIActivity --es id $moduleId
```

**Comment by Rem01Gaming** [comment]
Ah I don't know it's exists before, thanks 👍
